/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COM220.View;

import COM220.Control.ctrCliente;
import COM220.Control.ctrQuarto;
import COM220.Control.ctrReserva;
import COM220.Model.Cliente;
import COM220.Model.Quarto;
import COM220.Model.Reserva;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tiago
 */
public class AddReserva extends javax.swing.JFrame {

    private final ReservasView.ReservaAdapter adapter;
    private final ctrReserva controle;

    /**
     * Creates new form AddReserva
     */
    public AddReserva(ctrReserva controle, ReservasView.ReservaAdapter adapter) {
        initComponents();

        this.controle = controle;
        this.adapter = adapter;

        setLocationRelativeTo(null);

        lstQuartos.setModel(new QuartosDisponiveisAdapter());

        for (Cliente cl : new ctrCliente().listaDeClientes()) {
            cbClientes.addItem(cl);
        }

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sDataEntrada = new javax.swing.JSpinner();
        sDataSaida = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        sDesconto = new javax.swing.JSpinner();
        btnOK = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbClientes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstQuartos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Data de entrada");

        jLabel8.setText("Data de saída");

        sDataEntrada.setModel(new javax.swing.SpinnerDateModel());

        sDataSaida.setModel(new javax.swing.SpinnerDateModel());

        jLabel9.setText("Desconto");

        sDesconto.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel10.setText("Quartos");

        jLabel11.setText("Cliente");
        jLabel11.setToolTipText("");

        lstQuartos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstQuartos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(sDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(sDataSaida)
                                .addComponent(sDataEntrada)
                                .addComponent(cbClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        if (lstQuartos.getSelectedValuesList().size() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione um quarto!");
            return;
        }

        //try{
        //Adiciona um novo cliente.
        Reserva r = new Reserva(
                (Cliente) cbClientes.getSelectedItem(),
                ((Date) sDataEntrada.getValue()).getTime(),
                ((Date) sDataSaida.getValue()).getTime(),
                (double) sDesconto.getValue());
        r.setQuartos(lstQuartos.getSelectedValuesList());
        controle.addReserva(r);
        //Atualiza a tabela.
        adapter.fireTableDataChanged();
        //Fecha a janela.
        setVisible(false);
        dispose();
        //}catch( Exception e ){
        //}
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbClientes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstQuartos;
    private javax.swing.JSpinner sDataEntrada;
    private javax.swing.JSpinner sDataSaida;
    private javax.swing.JSpinner sDesconto;
    // End of variables declaration//GEN-END:variables

    private class QuartosDisponiveisAdapter extends AbstractListModel<Quarto> {

        private List<Quarto> quartos;

        public QuartosDisponiveisAdapter() {
            Calendar c = Calendar.getInstance();
            long a = c.getTimeInMillis();
            c.add(Calendar.MONTH, 12);
            long b = c.getTimeInMillis();

            quartos = new ctrReserva().verificaDisponibilidade(a, b);
        }

        @Override
        public int getSize() {
            return quartos.size();
        }

        @Override
        public Quarto getElementAt(int index) {
            return quartos.get(index);
        }
    }
}
